<?php print $this->doctype() ?>
<html>
    <head>
        <?php print $this->headMeta() ?>
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <?php print $this->headLink() ?>
        <?php print $this->headTitle() ?>
    </head>
    <body>

        <div class="container">
            <?php print $this->partial('_header.phtml') ?>
            <?php print $this->layout()->content ?>
            <?php print $this->partial('_footer.phtml') ?>
        </div>

        <?php print $this->headScript() ?>
    </body>
</html>
